version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    ports: 
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=devoure
      - POSTGRES_USER=devoure
      - POSTGRES_DB=blog

  backend:
    build:
      context: ../backend/.
    port:
      - "8000:8000"
    volumes:
      - ../backend/blog:/backend
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
    depends_on:
      - postgres
