# Generated by Django 4.0.5 on 2023-09-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_slug_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='emails',
            new_name='email',
        ),
    ]
